apiVersion: v1
kind: Pod
metadata:
  name: tidebox
  labels:
    app: tidebox
spec:
  containers:
  - name: tidebox
    image: quay.io/doubledensity/tidebox:0.2
    ports:
    - containerPort: 8090
      name: ffserver
    - containerPort: 22
      name: sshd
  imagePullSecrets:
    - name: myregistrykey
