apiVersion: v1
kind: Service
metadata:
  name: tideboxsvcs
spec:
  type: LoadBalancer
  ports:
    - 
      name: sshd
      port: 22
      targetPort: 22
    -
      name: ffserver
      port: 8090
      targetPort: 8090
  selector:
    app: tidebox
